version: '3.7'

services:
  web_server: 
    image: nginx:1.17.3-alpine
    volumes:
      - ./:/var/www/aussie_farm
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/nginxconfig.io:/etc/nginx/nginxconfig.io
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
    working_dir: /var/www
    networks: 
      default: 
        aliases:
          - aussie-farm.localhost
    ports: 
      - 80:80
    depends_on:
      - app

  app:
    build: 
      context: ./docker/php
      target: local
    image: laravel:php7.2_with_npm
    working_dir: /var/www/aussie_farm
    volumes:
      - ./:/var/www/aussie_farm
    depends_on: 
    - database_server

  database_server:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: aussie_farm
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: root
    networks:
      default:
        ipv4_address: 172.16.132.101
    volumes:
      - mysql_volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_volume:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.132.0/24
